name: Security Audit

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - review_requested
  push:
    branches:
      - main
  schedule:
    - cron: '45 12 * * *'

jobs:
  composer-audit:
    name: 'Composer Security Vulnerabilities Audit'
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup-php
      - uses: ./.github/actions/setup-composer

      - name: 'Check security vulnerabilities'
        run: composer audit --locked

  psalm-security:
    name: 'Psalm Security Scan'
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Psalm Security Scan'
        uses: psalm/psalm-github-security-scan@f3e6fd9432bc3e44aec078572677ce9d2ef9c287

      - name: 'Upload Security Analysis results to GitHub'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
